server:
  port: 8091

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
#    # 访问令牌获取 URL，自定义的
#    access-token-uri: http://127.0.0.1:8080/oauth/token